-- Canonical catalogue from docs/seguridad/modelo-autorizacion.md v1.2.
-- Keep earlier migrations intact for existing databases.
ALTER TABLE permiso DROP CONSTRAINT permiso_alcance_check;
ALTER TABLE permiso ADD CONSTRAINT permiso_alcance_check
    CHECK (alcance IN ('GLOBAL', 'PROPIO', 'PUBLICADO', 'ORG', 'POSTULANTE', 'INSCRIPTO'));
DELETE FROM permiso;
INSERT INTO permiso (rol, accion, alcance) VALUES
    ('VISITANTE', 'cuenta.registrar', 'GLOBAL'),
    ('VISITANTE', 'sesion.iniciar', 'GLOBAL'),
    ('TALENTO', 'sesion.cerrar', 'PROPIO'),
    ('ADMIN', 'sesion.cerrar', 'PROPIO'),
    ('RECLUTADOR', 'sesion.cerrar', 'PROPIO'),
    ('EDITOR', 'sesion.cerrar', 'PROPIO'),
    ('ADMIN', 'sesion.reautenticar', 'PROPIO'),
    ('TALENTO', 'cuenta.gestionar', 'PROPIO'),
    ('ADMIN', 'cuenta.gestionar', 'PROPIO'),
    ('RECLUTADOR', 'cuenta.gestionar', 'PROPIO'),
    ('EDITOR', 'cuenta.gestionar', 'PROPIO'),
    ('TALENTO', 'perfil.gestionar', 'PROPIO'),
    ('ADMIN', 'perfil.ver_postulante', 'POSTULANTE'),
    ('RECLUTADOR', 'perfil.ver_postulante', 'POSTULANTE'),
    ('VISITANTE', 'catalogo.ver', 'PUBLICADO'),
    ('TALENTO', 'catalogo.ver', 'PUBLICADO'),
    ('ADMIN', 'catalogo.ver', 'PUBLICADO'),
    ('RECLUTADOR', 'catalogo.ver', 'PUBLICADO'),
    ('EDITOR', 'catalogo.ver', 'PUBLICADO'),
    ('ADMIN', 'curso.gestionar', 'ORG'),
    ('EDITOR', 'curso.gestionar', 'ORG'),
    ('ADMIN', 'curso.ver_borrador', 'ORG'),
    ('EDITOR', 'curso.ver_borrador', 'ORG'),
    ('ADMIN', 'material.subir', 'ORG'),
    ('EDITOR', 'material.subir', 'ORG'),
    ('TALENTO', 'material.descargar', 'INSCRIPTO'),
    ('ADMIN', 'material.descargar', 'ORG'),
    ('EDITOR', 'material.descargar', 'ORG'),
    ('TALENTO', 'inscripcion.crear', 'PUBLICADO'),
    ('TALENTO', 'inscripcion.ver', 'PROPIO'),
    ('TALENTO', 'leccion.completar', 'INSCRIPTO'),
    ('TALENTO', 'entregable.responder', 'INSCRIPTO'),
    ('ADMIN', 'inscripcion.ver_inscriptos', 'ORG'),
    ('EDITOR', 'inscripcion.ver_inscriptos', 'ORG'),
    ('TALENTO', 'oferta.ver', 'PUBLICADO'),
    ('ADMIN', 'oferta.ver', 'PUBLICADO'),
    ('RECLUTADOR', 'oferta.ver', 'PUBLICADO'),
    ('EDITOR', 'oferta.ver', 'PUBLICADO'),
    ('ADMIN', 'oferta.gestionar', 'ORG'),
    ('RECLUTADOR', 'oferta.gestionar', 'ORG'),
    ('TALENTO', 'postulacion.crear', 'PUBLICADO'),
    ('TALENTO', 'postulacion.ver', 'PROPIO'),
    ('ADMIN', 'postulacion.ver_listado', 'ORG'),
    ('RECLUTADOR', 'postulacion.ver_listado', 'ORG'),
    ('ADMIN', 'postulacion.cambiar_estado', 'ORG'),
    ('RECLUTADOR', 'postulacion.cambiar_estado', 'ORG'),
    ('TALENTO', 'curriculum.subir', 'PROPIO'),
    ('TALENTO', 'curriculum.descargar', 'PROPIO'),
    ('ADMIN', 'curriculum.descargar', 'POSTULANTE'),
    ('RECLUTADOR', 'curriculum.descargar', 'POSTULANTE'),
    ('ADMIN', 'staff.invitar', 'ORG'),
    ('ADMIN', 'staff.cambiar_rol', 'ORG'),
    ('ADMIN', 'staff.dar_baja', 'ORG'),
    ('ADMIN', 'staff.ver', 'ORG');
