# Base en memoria para levantar la aplicación sin Docker: --spring.profiles.active=h2
spring:
  datasource:
    url: jdbc:h2:mem:xperience;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: ""
